name: Release image

on:
  push:
    branches:
      - master

jobs:
  CI:
    uses: enspirit/attitude/.github/workflows/integration.yml@master

  release:
    needs: CI
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - uses: act10ns/slack@v1
        with:
          status: starting
          channel: '#opensource-cicd'

      - uses: actions/checkout@v2

      - name: Building images
        id: image-build
        run: make image

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Release images
        id: images-push
        run: make image.push

      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: '#opensource-cicd'
        if: always()
